services:
  - type: web
    name: paperpal-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health/
    envVars:
      - key: APP_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: paperpal_db
      - key: FRONTEND_ORIGIN
        sync: false

  - type: web
    name: paperpal-frontend
    runtime: python
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: BACKEND_BASE_URL
        sync: false
