[server]
maxUploadSize = 1
headless = true
enableXsrfProtection = true

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C1F26"
textColor = "#FAFAFA"
font = "sans serif"
